homepage:
  url: /
  params: {controller: blog, action: index}

# View the post
view_post:
  url: /:year/:month/:day/:slug
  params: {controller: blog, action: show}

# view by catagory
catagory:
  url: /catagories/:slug
  params: {controller: catagory, action: show}

# view by tag
tag:
  url: /tags/:slug
  params: {controller: tag, action: show}

archive:
  url: /archive
  params: {controller: blog, action: archive}

feed:
  url: /feed.:format
  params: {controller: blog, action: index, format: rss}
  
page:
  url: /page/:slug
  params: {controller: page, action: show}


# ---Default routes---
default_index:
  url: /:controller
  params: {action: index}

default:
  url: /:controller/:action
