<?php

/**
 * Catagory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Catagory extends BaseCatagory
{
    public static function getAll()
    {
    	return Doctrine_Query::create()
                        ->from('Catagory c')->orderBy('c.created_at DESC')->fetchArray();
    }
}