<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Post extends BasePost
{
	public static function findBySlug($slug)
	{
		$q = Doctrine_Query::create()->from('Post p')->where('p.slug = ?', $slug);
		return $q->fetchOne();
	}
	
	public function toParams()
	{
		$year = date_format($this->created_at, "%Y");
		$month = date_format($this->created_at, "%m");
		$day = date_format($this->created_at, "%d");
		
		return http_build_query(array(
				'year' => $year,
				'month' => $month,
				'day' => $day,
				'slug' => $this->slug));
	}
	public function preSavess(Doctrine_Event $event)
	{
		// may have empty slug
//		if(!$this->slug) $this->slug = md5(rand(10));
		return self::preSave($event);
	}
}