
encode: "utf-8"

use_database: true
enable_toolbar: true

default_layout: application

default_500_handler: false
url_rewrite: true

middlewares:
  - CommonMiddleware
  - ToolBarMiddleware
  

# Tag helper is required by Url and Asset helper
default_helpers: [Tag, Asset, Url, View]
  
views:
  - rtView
  - rtMarkdownView