detect_relations: true

User:
  actAs: [Timestampable]
  columns:
    username: string
    password: string
    first_name: string
    last_name:  string
  
Settings:
  columns:
    blog_name: string
    max_post:   integer
  
Post:
  actAs:
    Timestampable:
    Sluggable:
      fields: [title]
      name: slug    # defaults to 'slug'
      type: string  # defaults to 'clob'
      length: 255   # defaults to null. clob doesn't require a length
      builder: [rtUtils, urlize]  # Doctrine urlize have problem with chinese
  columns:
    user_id: integer
    catagory_id: integer
    type: string  # post, page
    title: string
    slug: string
    format: string
    raw_content: string
    content: string
    
Catagory:
  actAs:
    Timestampable:
    Sluggable:
      fields: [name]
      name: slug
      type: string
      lenght: 255
      builder: [rtUtils, urlize]
  columns:
    name: string
    slug: string